import { statusOf, type Metric, type Severity } from "./model";

/**
 * THE READING (§6.128).
 *
 * The dashboard this was modelled on opens each tab with a consultant's sentence — "Repays in the base
 * case, but has no cushion under stress" — and that sentence is most of why it lands. A grid of dials
 * tells a client what is true; the sentence tells them what it MEANS, which is the part they are paying
 * a consultant for.
 *
 * SO IT IS WRITTEN, NOT GENERATED BY A MODEL, and that is a deliberate refusal.
 *
 * > A model asked to summarise nine ratios will produce a fluent paragraph, and nothing in the paragraph
 * > is checkable. This is a verdict on somebody's business, headed for a bank. Every sentence here can be
 * > traced to a metric, a band and a threshold — and if the sentence is wrong, the rule that produced it
 * > can be found and fixed, which is not true of a good-sounding paragraph.
 *
 * The rules are simple on purpose: the worst thing first, then the next, then what to do about each.
 */

export type CapabilityKind = "grow" | "borrow" | "sell";

export type Verdict = {
  headline: string;
  /** One per problem worth naming, in the order a reader should meet them. Already sentences. */
  paragraphs: { lead: string; body: string }[];
  /** What to do, ranked. Empty when nothing is wrong, which is itself worth saying. */
  actions: string[];
  /** The question the tab answers, shown above the headline. */
  question: string;
};

/** Worst first, then by how much the metric matters. A tie is broken by weight, never by order written. */
function ranked(metrics: Metric[], weights: Record<string, number>): { m: Metric; s: Severity }[] {
  const rank: Record<Severity, number> = { bad: 0, watch: 1, good: 2 };
  return metrics
    .map((m) => ({ m, s: statusOf(m.value, m.bands) }))
    .filter((x): x is { m: Metric; s: Severity } => x.s !== null)
    .sort((a, b) => rank[a.s] - rank[b.s] || (weights[b.m.key] ?? 1) - (weights[a.m.key] ?? 1));
}

/**
 * ONE ACTION PER PROBLEM, and none that the app cannot stand behind.
 *
 * Every line is a thing the client can do this quarter, phrased as an instruction rather than an
 * observation — "bring debtor days down" rather than "debtor days are high", which the card above already
 * said. Nothing here invents a number: where an action needs one, it points at the screen that holds it.
 */
/*
 * An action can depend on the reading (§6.129.2). The margin action was rewritten for a LOSS in §6.129.1 and
 * then shown on SEQ the moment Nic's own add-backs lifted normalised earnings to +0.4% — "there is no earnings
 * figure to sell on" beside a card saying there is one. Same measure, two different problems, two sentences.
 */
type Action = string | ((m: Metric) => string);
const ACTIONS: Record<string, Action> = {
  /* Grow */
  operatingMargin: "Fix the loss before growing into it — this is the one thing on the page that has to change first.",
  lowestCash: "Fix the low month before anything else — bring invoicing forward, stage the spending, or arrange an overdraft to cover it.",
  cashConversion: "Chase the gap between profit and cash: it is sitting in unpaid invoices or in stock.",
  cashCycle: "Shorten the cycle — invoice on delivery, tighten terms, or hold less stock. Every day taken out is cash back.",
  workingCapitalPerDollar: "Every new sale is tying up cash. Ask for deposits or shorter terms on new work before you chase more of it.",
  returnOnPlan: "The spending does not earn enough. Stage it, or cut the part of it that is not tied to new revenue.",
  incrementalMargin: "Put a floor under the margin on new work, or the growth makes the business bigger and no better off.",
  operatingLeverage: "Overheads are growing with sales. Find the costs that should not have to rise before you add more volume.",
  revenueGrowth: "There is no growth in the forecast to fund. Revisit the sales lines before using this page.",
  /*
   * Borrow. REWRITTEN FOR THE DEBT THE PLAN CARRIES (§6.129) — every one of these used to instruct the
   * client about a loan they had typed into the dashboard, and on a plan with real borrowing in it that read
   * as advice about a loan that did not exist. "Reduce it, lengthen the term" is not something you do to
   * debt you have already drawn.
   */
  dscr: "The debt already in the plan is more than this cash flow covers. Refinance it longer, pay some down, or raise the earnings before adding to it.",
  dscrStressed: "The cover holds today and not in a bad year. Ask for interest-only, or build a buffer that carries the repayments through a soft quarter.",
  runway: "Build the cash buffer. An overdraft costs little unused and is the cheapest insurance here.",
  leverage: "Total debt is heavy against earnings. Pay something down, or raise the earnings, before adding more.",
  lvr: "Most of the security is already spoken for. There is little left to offer a lender for anything further.",
  quickRatio: "Short-term bills depend on shifting stock. Collect faster, or hold less.",
  currentRatio: "Short-term obligations are close to short-term assets. Watch it before taking on more.",
  /* True whether the operating profit is thin or absent — the old wording assumed there was one. */
  interestCover: "Interest is heavy against what the business earns. Refinance it or pay some down before borrowing more.",
  /* Sell */
  priceMultiple: "Reset the price to the top of your comparable range, or wait and sell stronger numbers.",
  transferability: "Fix the weakest transferability factor before going to market. A buyer discounts for it far harder than you would.",
  normalisedMargin: (m) => m.value !== null && m.value < 0
    ? "There is no earnings figure to sell on. Get the business into profit and hold it there for a year — nothing else on this tab matters until then."
    : "The margin is thin for a sale. Either improve it for a year, or expect the multiple to reflect it.",
  fcfYield: "At this price a buyer's money earns too little. The price is the thing to move.",
  recurringShare: "Convert repeat customers onto something contracted before you go to market — it is the cheapest value you can add.",
  largestCustomer: "Work out your largest customer's share from your sales ledger. If it is above 20%, secure that contract on assignable terms before a buyer asks.",
  freeCashFlow: "Thin free cash flow after keeping the assets going. A buyer will notice the capital this business needs.",
  roic: "The business earns little on the capital it ties up, which caps what anyone will pay for it.",
};

const HEAD = {
  grow: {
    none: "Not enough of the plan is filled in to judge the growth",
    bad: "The growth plan does not fund itself",
    watch: "Worth doing, but it will be tight on cash",
    good: "The growth stands up",
  },
  borrow: {
    none: "Not enough of the plan is filled in to judge the borrowing",
    bad: "The debt is more than this business can carry",
    watch: "Repays in the base case, with little cushion",
    good: "The business carries its debt, with room to spare",
  },
  sell: {
    none: "Not enough of the plan is filled in to judge a sale",
    bad: "Not ready to sell at this price",
    watch: "Saleable, with work to do first",
    good: "This would stand up to a buyer",
  },
} as const;

const QUESTION = {
  grow: "Can the business increase profit while funding the cash, people and assets that growth needs?",
  borrow: "Can the business repay what it owes on time, including if trading gets worse — and would a lender add to it?",
  sell: "Would the earnings and the customers survive a change of owner, and is the price justified?",
} as const;

export function verdict(
  kind: CapabilityKind,
  metrics: Metric[],
  weights: Record<string, number>,
  score: number | null,
): Verdict {
  const question = QUESTION[kind];
  if (score === null) {
    return {
      question, headline: HEAD[kind].none, actions: [],
      paragraphs: [{
        lead: "Nothing here is guessed.",
        body: "Every figure on this page is read from your own forecast. Fill in your sales lines and costs and it answers itself — each card below already says what it is waiting for.",
      }],
    };
  }

  const order = ranked(metrics, weights);
  const problems = order.filter((x) => x.s !== "good");
  const band: Severity = score < 50 ? "bad" : score < 70 ? "watch" : "good";

  /*
   * THE GOOD NEWS IS NAMED FIRST WHEN THERE IS ANY, because a page that opens on what is wrong reads as a
   * telling-off, and a client who has built something sound should be told so before being given a list.
   */
  const best = order.find((x) => x.s === "good");
  const paragraphs: Verdict["paragraphs"] = [];
  if (best && band !== "bad") paragraphs.push({ lead: `${best.m.name} is holding up.`, body: best.m.note });
  for (const p of problems.slice(0, 3)) paragraphs.push({ lead: `${p.m.name}.`, body: p.m.note });
  if (!problems.length) {
    paragraphs.push({
      lead: "Nothing is flagged.",
      body: "Every measure this page can compute sits in its healthy band. That is worth saying plainly — and worth re-reading once the forecast changes.",
    });
  }

  return {
    question,
    headline: HEAD[kind][band],
    paragraphs,
    actions: problems
      .map((p) => { const a = ACTIONS[p.m.key]; return typeof a === "function" ? a(p.m) : a; })
      .filter((a): a is string => !!a)
      .slice(0, 4),
  };
}

/**
 * WHAT A BUYER'S ADVISER WILL ASK (§6.129.2).
 *
 * The dashboard this was modelled on closed its selling tab with six due-diligence questions, and they were
 * the most useful thing on it: a seller who has read them before the first meeting has answers instead of
 * surprises. Its questions were hand-written for one sample business. These are written by RULE, from this
 * plan's own weak measures, for the reason the verdict is (§6.128): every question can be traced to the
 * measure that raised it, and a question that does not apply to this business is never asked.
 *
 * Ordered by what a buyer tests first — earnings, then price, then dependence on the owner — and capped at
 * six, because a list of fifteen is a list nobody prepares for.
 */
export function buyerQuestions(
  metrics: Metric[],
  facts: {
    money: (v: number) => string;
    addBacks: number | null;
    transfer: { key: string; label: string; score: number | null }[];
    knowsCustomers: boolean;
    /** The largest customers, once the plan records them (§6.129.3). */
    customers?: { name: string; share: number | null; assignable: boolean | null; endsWithinYear: boolean }[];
  },
): string[] {
  const m = facts.money;
  const at = (k: string) => metrics.find((x) => x.key === k);
  const s = (k: string) => { const x = at(k); return x ? statusOf(x.value, x.bands) : null; };
  const q: string[] = [];

  const margin = at("normalisedMargin");
  if (margin && margin.value !== null && margin.value < 0) {
    q.push("Why does the business lose money before interest, tax and depreciation — and what, specifically, changes that?");
  } else if (s("normalisedMargin") === "bad") {
    q.push("Why is the margin below what similar businesses earn, and is it a price problem or a cost problem?");
  }

  const price = at("priceMultiple");
  if (price && price.value !== null && s("priceMultiple") !== "good") {
    q.push(`How is ${price.display} earnings justified against what comparable businesses have sold for?`);
  }

  if (facts.addBacks && facts.addBacks > 0) {
    q.push(`Which of the ${m(facts.addBacks)} in owner add-backs will survive a quality-of-earnings review, and what document supports each one?`);
  }

  /* Owner dependence, factor by factor — the weakest judgements become the sharpest questions. */
  const weak = facts.transfer.filter((t) => t.score !== null && t.score <= 2);
  const PER_FACTOR: Record<string, string> = {
    owner: "What happens to the business in the month after the owner leaves?",
    customers: "Who, other than the owner, knows the largest customers — and would they stay?",
    processes: "Where is it written down how the work is actually done?",
    staff: "Which of the people who matter are tied in, and on what terms?",
    contracts: "Which contracts can be assigned to a new owner, and which end at a change of control?",
    systems: "Are the books and systems something a buyer's accountant can rely on without rebuilding them?",
  };
  for (const w of weak) if (PER_FACTOR[w.key]) q.push(PER_FACTOR[w.key]);
  if (facts.transfer.every((t) => t.score === null)) {
    q.push("Would the business keep trading if the owner stopped turning up? It has not been assessed yet.");
  }

  /*
   * ONCE THE CUSTOMERS ARE KNOWN, THE QUESTIONS GET NAMES (§6.129.3). "What happens if your largest customer
   * leaves" is a question; "what happens if Metricon stops buying" is the one a buyer actually asks.
   */
  const cs = facts.customers ?? [];
  const top = [...cs].filter((c) => c.share !== null).sort((a, b) => (b.share ?? 0) - (a.share ?? 0))[0];
  if (top && (top.share ?? 0) > 20) {
    q.push(`What happens to the earnings if ${top.name} — ${Math.round((top.share ?? 0) * 10) / 10}% of sales — stops buying?`);
  }
  if (cs.some((c) => c.assignable === false)) {
    q.push("Which customer contracts end on a change of ownership, and can they be renegotiated before the sale?");
  }
  const ending = cs.find((c) => c.endsWithinYear);
  if (ending) q.push(`${ending.name}'s contract ends within the year. Has it been renewed, and on what terms?`);

  /*
   * THE ONE QUESTION THIS APP CANNOT ANSWER FOR THE CLIENT, asked every time until it can. Customer
   * concentration is the first thing a buyer's adviser looks for, and the plan does not yet record customers.
   */
  if (!facts.knowsCustomers) {
    q.push("Who are the largest customers, what share of revenue does each one hold, and when do their contracts end?");
  }

  const conv = at("cashConversion");
  if (conv && conv.value !== null && s("cashConversion") === "bad") {
    q.push(`Why does only ${conv.display} of earnings arrive as cash?`);
  }
  const fcf = at("freeCashFlow");
  if (fcf && fcf.value !== null && fcf.value < 0) {
    q.push("What does it cost each year just to keep the assets standing still — and who funds that after settlement?");
  }
  if (s("recurringShare") === "bad") {
    q.push("How much of next year's revenue is already contracted, and on what terms?");
  }
  if (s("largestProduct") === "bad") {
    q.push("What happens to the earnings if the biggest product line stops selling?");
  }
  const pay = at("leadershipPay");
  if (s("leadershipPay") === "bad" || (pay && pay.value === null && pay.sub === undefined && pay.missing?.includes("not positive"))) {
    q.push("What would it cost to replace the owner with a manager paid at market rate?");
  }
  if (s("assetIntensity") === "bad") {
    q.push("What plant falls due for replacement in the next three years, and at what cost?");
  }
  if (s("revenueGrowth") === "bad") {
    q.push("Why is revenue flat, and what would make it grow under a new owner?");
  }

  return q.slice(0, 6);
}
