import { statusOf, type Metric, type Severity } from "./model";

/**
 * THE READING (§6.128).
 *
 * The dashboard this was modelled on opens each tab with a consultant's sentence — "Repays in the base
 * case, but has no cushion under stress" — and that sentence is most of why it lands. A grid of dials
 * tells a client what is true; the sentence tells them what it MEANS, which is the part they are paying
 * a consultant for.
 *
 * SO IT IS WRITTEN, NOT GENERATED BY A MODEL, and that is a deliberate refusal.
 *
 * > A model asked to summarise nine ratios will produce a fluent paragraph, and nothing in the paragraph
 * > is checkable. This is a verdict on somebody's business, headed for a bank. Every sentence here can be
 * > traced to a metric, a band and a threshold — and if the sentence is wrong, the rule that produced it
 * > can be found and fixed, which is not true of a good-sounding paragraph.
 *
 * The rules are simple on purpose: the worst thing first, then the next, then what to do about each.
 */

export type CapabilityKind = "grow" | "borrow" | "sell";

export type Verdict = {
  headline: string;
  /** One per problem worth naming, in the order a reader should meet them. Already sentences. */
  paragraphs: { lead: string; body: string }[];
  /** What to do, ranked. Empty when nothing is wrong, which is itself worth saying. */
  actions: string[];
  /** The question the tab answers, shown above the headline. */
  question: string;
};

/** Worst first, then by how much the metric matters. A tie is broken by weight, never by order written. */
function ranked(metrics: Metric[], weights: Record<string, number>): { m: Metric; s: Severity }[] {
  const rank: Record<Severity, number> = { bad: 0, watch: 1, good: 2 };
  return metrics
    .map((m) => ({ m, s: statusOf(m.value, m.bands) }))
    .filter((x): x is { m: Metric; s: Severity } => x.s !== null)
    .sort((a, b) => rank[a.s] - rank[b.s] || (weights[b.m.key] ?? 1) - (weights[a.m.key] ?? 1));
}

/**
 * ONE ACTION PER PROBLEM, and none that the app cannot stand behind.
 *
 * Every line is a thing the client can do this quarter, phrased as an instruction rather than an
 * observation — "bring debtor days down" rather than "debtor days are high", which the card above already
 * said. Nothing here invents a number: where an action needs one, it points at the screen that holds it.
 */
/*
 * An action can depend on the reading (§6.129.2). The margin action was rewritten for a LOSS in §6.129.1 and
 * then shown on SEQ the moment Nic's own add-backs lifted normalised earnings to +0.4% — "there is no earnings
 * figure to sell on" beside a card saying there is one. Same measure, two different problems, two sentences.
 */
type Action = string | ((m: Metric) => string);
const ACTIONS: Record<string, Action> = {
  /* Grow */
  operatingMargin: "Fix the loss before trying to grow. This has to change first.",
  lowestCash: "Fix the month the bank runs low first: send invoices sooner, spread out the spending, or arrange an overdraft.",
  cashConversion: "Chase the unpaid invoices and cut back stock — that is where the missing cash is.",
  cashCycle: "Get paid faster: invoice when the job is done, give shorter payment terms, or hold less stock. Every day saved is cash back.",
  workingCapitalPerDollar: "Every new sale is tying up cash. Ask for deposits or shorter payment terms on new work before chasing more of it.",
  returnOnPlan: "The money spent on growing does not earn enough back. Spend it in stages, or cut what is not bringing in new sales.",
  incrementalMargin: "Set a minimum profit on new work. Otherwise the business gets bigger but not better off.",
  operatingLeverage: "Costs are rising with sales. Find the costs that should not have to rise before selling more.",
  revenueGrowth: "The plan shows no growth. Check the sales figures before relying on this page.",
  /*
   * Borrow. REWRITTEN FOR THE DEBT THE PLAN CARRIES (§6.129) — every one of these used to instruct the
   * client about a loan they had typed into the dashboard, and on a plan with real borrowing in it that read
   * as advice about a loan that did not exist. "Reduce it, lengthen the term" is not something you do to
   * debt you have already drawn.
   */
  dscr: "The loans are bigger than the cash coming in can pay. Ask the bank for a longer term, pay some off, or lift profit before borrowing more.",
  dscrStressed: "The loans can be paid in a normal year but not a bad one. Ask for interest-only payments, or build up cash to cover a slow few months.",
  runway: "Build up cash in the bank. An overdraft costs little if unused and is the cheapest safety net.",
  leverage: "Debt is high compared with profit. Pay some off, or lift profit, before borrowing more.",
  lvr: "Most of what the business owns is already backing loans. There is little left to offer a lender.",
  quickRatio: "Paying the bills depends on selling stock. Collect money faster, or hold less stock.",
  currentRatio: "Bills due soon are close to what can be turned into cash soon. Watch this before taking on more.",
  /* True whether the operating profit is thin or absent — the old wording assumed there was one. */
  interestCover: "Interest takes a big bite out of profit. Get a better rate or pay some debt off before borrowing more.",
  /* Sell */
  priceMultiple: "Bring the price down to what similar businesses sold for, or wait and sell once the numbers are stronger.",
  transferability: "Fix the weakest area before putting the business up for sale. A buyer will knock more off the price for it than you would expect.",
  normalisedMargin: (m) => m.value !== null && m.value < 0
    ? "There is no profit to sell. Get the business making a profit and keep it there for a year — nothing else on this tab matters until then."
    : "The profit margin is thin for a sale. Improve it for a year, or expect a lower price.",
  fcfYield: "At this price a buyer's money earns too little. The price needs to come down.",
  recurringShare: "Put repeat customers on contracts before selling — it is the cheapest way to add value.",
  largestCustomer: "Find your biggest customer's share of sales. If it is over 20%, get a contract that passes to a new owner before a buyer asks.",
  freeCashFlow: "Little cash is left after keeping the equipment going. A buyer will notice how much money the business needs.",
  roic: "The business earns little on the money tied up in it, which limits what anyone will pay for it.",
  largestProduct: "Grow sales of the other products, so the business does not depend on one.",
  leadershipPay: "Profit has to grow, or the pay of the people running it has to come down, before a buyer will pay much.",
  assetIntensity: "List what equipment will need replacing and when — a buyer will ask before making an offer.",
};

const HEAD = {
  grow: {
    none: "Not enough of the plan is filled in to judge growth yet",
    bad: "The growth plan does not pay for itself",
    watch: "Worth doing, but cash will be tight",
    good: "The growth plan works",
  },
  borrow: {
    none: "Not enough of the plan is filled in to judge borrowing yet",
    bad: "The loans are more than this business can pay",
    watch: "The loans can be paid in a normal year, with little to spare",
    good: "The business can pay its loans, with room to spare",
  },
  sell: {
    none: "Not enough of the plan is filled in to judge a sale yet",
    bad: "Not ready to sell at this price",
    watch: "Could be sold, with work to do first",
    good: "A buyer would take this seriously",
  },
} as const;

const QUESTION = {
  grow: "Can the business make more profit as it grows, and pay for the cash, people and equipment that growth needs?",
  borrow: "Can the business pay its loans on time, even in a bad year — and would a bank lend it more?",
  sell: "Would the profit and the customers stay with a new owner, and is the price fair?",
} as const;

/**
 * THE PLAIN ACTION FOR ONE CARD (§6.178) — for a card none of the money levers move (loan cover in a bad year
 * that still loses money, revenue from ongoing clients). Every card not in the green says how to improve it.
 */
export function actionFor(m: Metric): string | null {
  if (m.action) return m.action;
  const a = ACTIONS[m.key];
  return a === undefined ? null : typeof a === "function" ? a(m) : a;
}

export function verdict(
  kind: CapabilityKind,
  metrics: Metric[],
  weights: Record<string, number>,
  score: number | null,
): Verdict {
  const question = QUESTION[kind];
  if (score === null) {
    return {
      question, headline: HEAD[kind].none, actions: [],
      paragraphs: [{
        lead: "Nothing here is guessed.",
        body: "Every figure on this page comes from your own plan. Fill in your sales and costs and it will fill in — each box below says what it is waiting for.",
      }],
    };
  }

  const order = ranked(metrics, weights);
  const problems = order.filter((x) => x.s !== "good");
  const band: Severity = score < 50 ? "bad" : score < 70 ? "watch" : "good";

  /*
   * THE GOOD NEWS IS NAMED FIRST WHEN THERE IS ANY, because a page that opens on what is wrong reads as a
   * telling-off, and a client who has built something sound should be told so before being given a list.
   */
  const best = order.find((x) => x.s === "good");
  const paragraphs: Verdict["paragraphs"] = [];
  if (best && band !== "bad") paragraphs.push({ lead: `${best.m.name} is in good shape.`, body: best.m.note });
  for (const p of problems.slice(0, 3)) paragraphs.push({ lead: `${p.m.name}.`, body: p.m.note });
  if (!problems.length) {
    paragraphs.push({
      lead: "Nothing is flagged.",
      body: "Every measure on this page is in the green. Check again whenever the plan changes.",
    });
  }

  return {
    question,
    headline: HEAD[kind][band],
    paragraphs,
    actions: problems
      .map((p) => { if (p.m.action) return p.m.action; const a = ACTIONS[p.m.key]; return typeof a === "function" ? a(p.m) : a; })
      .filter((a): a is string => !!a)
      .slice(0, 4),
  };
}

/**
 * WHAT A BUYER'S ADVISER WILL ASK (§6.129.2).
 *
 * The dashboard this was modelled on closed its selling tab with six due-diligence questions, and they were
 * the most useful thing on it: a seller who has read them before the first meeting has answers instead of
 * surprises. Its questions were hand-written for one sample business. These are written by RULE, from this
 * plan's own weak measures, for the reason the verdict is (§6.128): every question can be traced to the
 * measure that raised it, and a question that does not apply to this business is never asked.
 *
 * Ordered by what a buyer tests first — earnings, then price, then dependence on the owner — and capped at
 * six, because a list of fifteen is a list nobody prepares for.
 */
export function buyerQuestions(
  metrics: Metric[],
  facts: {
    money: (v: number) => string;
    addBacks: number | null;
    transfer: { key: string; label: string; score: number | null }[];
    knowsCustomers: boolean;
    /** The largest customers, once the plan records them (§6.129.3). */
    customers?: { name: string; share: number | null; assignable: boolean | null; endsWithinYear: boolean }[];
  },
): string[] {
  const m = facts.money;
  const at = (k: string) => metrics.find((x) => x.key === k);
  const s = (k: string) => { const x = at(k); return x ? statusOf(x.value, x.bands) : null; };
  const q: string[] = [];

  const margin = at("normalisedMargin");
  if (margin && margin.value !== null && margin.value < 0) {
    q.push("Why does the business lose money before interest, tax and depreciation — and what exactly will change that?");
  } else if (s("normalisedMargin") === "bad") {
    q.push("Why is the profit margin lower than similar businesses — is it the prices or the costs?");
  }

  const price = at("priceMultiple");
  if (price && price.value !== null && s("priceMultiple") !== "good") {
    q.push(`How is ${price.display} earnings justified against what comparable businesses have sold for?`);
  }

  if (facts.addBacks && facts.addBacks > 0) {
    q.push(`Which of the ${m(facts.addBacks)} in owner add-backs will survive a quality-of-earnings review, and what document supports each one?`);
  }

  /* Owner dependence, factor by factor — the weakest judgements become the sharpest questions. */
  const weak = facts.transfer.filter((t) => t.score !== null && t.score <= 2);
  const PER_FACTOR: Record<string, string> = {
    owner: "What happens to the business in the month after the owner leaves?",
    customers: "Who, other than the owner, knows the largest customers — and would they stay?",
    processes: "Where is it written down how the work is actually done?",
    staff: "Which of the people who matter are tied in, and on what terms?",
    contracts: "Which contracts can be assigned to a new owner, and which end at a change of control?",
    systems: "Could a buyer's accountant rely on the books and systems as they are?",
  };
  for (const w of weak) if (PER_FACTOR[w.key]) q.push(PER_FACTOR[w.key]);
  if (facts.transfer.every((t) => t.score === null)) {
    q.push("Would the business keep running if the owner stopped turning up? This has not been checked yet.");
  }

  /*
   * ONCE THE CUSTOMERS ARE KNOWN, THE QUESTIONS GET NAMES (§6.129.3). "What happens if your largest customer
   * leaves" is a question; "what happens if Metricon stops buying" is the one a buyer actually asks.
   */
  const cs = facts.customers ?? [];
  const top = [...cs].filter((c) => c.share !== null).sort((a, b) => (b.share ?? 0) - (a.share ?? 0))[0];
  if (top && (top.share ?? 0) > 20) {
    q.push(`What happens to the earnings if ${top.name} — ${Math.round((top.share ?? 0) * 10) / 10}% of sales — stops buying?`);
  }
  if (cs.some((c) => c.assignable === false)) {
    q.push("Which customer contracts end if the business is sold, and can they be changed before the sale?");
  }
  const ending = cs.find((c) => c.endsWithinYear);
  if (ending) q.push(`${ending.name}'s contract ends within the year. Has it been renewed, and on what terms?`);

  /*
   * THE ONE QUESTION THIS APP CANNOT ANSWER FOR THE CLIENT, asked every time until it can. Customer
   * concentration is the first thing a buyer's adviser looks for, and the plan does not yet record customers.
   */
  if (!facts.knowsCustomers) {
    q.push("Who are the biggest customers, what share of sales does each one make up, and when do their contracts end?");
  }

  const conv = at("cashConversion");
  if (conv && conv.value !== null && s("cashConversion") === "bad") {
    q.push(`Why does only ${conv.display} of earnings arrive as cash?`);
  }
  const fcf = at("freeCashFlow");
  if (fcf && fcf.value !== null && fcf.value < 0) {
    q.push("What does it cost each year just to keep the equipment going — and who pays for that after the sale?");
  }
  if (s("recurringShare") === "bad") {
    q.push("How much of next year's sales is already locked in by contracts, and on what terms?");
  }
  if (s("largestProduct") === "bad") {
    q.push("What happens to the earnings if the biggest product line stops selling?");
  }
  const pay = at("leadershipPay");
  if (s("leadershipPay") === "bad" || (pay && pay.value === null && pay.sub === undefined && pay.missing?.includes("no profit to pay it from"))) {
    q.push("What would it cost to replace the owner with a manager paid at market rate?");
  }
  if (s("assetIntensity") === "bad") {
    q.push("What plant falls due for replacement in the next three years, and at what cost?");
  }
  if (s("revenueGrowth") === "bad") {
    q.push("Why is revenue flat, and what would make it grow under a new owner?");
  }

  return q.slice(0, 6);
}
