import { statusOf, type Metric, type Severity } from "./model";

/**
 * THE READING (§6.128).
 *
 * The dashboard this was modelled on opens each tab with a consultant's sentence — "Repays in the base
 * case, but has no cushion under stress" — and that sentence is most of why it lands. A grid of dials
 * tells a client what is true; the sentence tells them what it MEANS, which is the part they are paying
 * a consultant for.
 *
 * SO IT IS WRITTEN, NOT GENERATED BY A MODEL, and that is a deliberate refusal.
 *
 * > A model asked to summarise nine ratios will produce a fluent paragraph, and nothing in the paragraph
 * > is checkable. This is a verdict on somebody's business, headed for a bank. Every sentence here can be
 * > traced to a metric, a band and a threshold — and if the sentence is wrong, the rule that produced it
 * > can be found and fixed, which is not true of a good-sounding paragraph.
 *
 * The rules are simple on purpose: the worst thing first, then the next, then what to do about each.
 */

export type CapabilityKind = "grow" | "borrow" | "sell";

export type Verdict = {
  headline: string;
  /** One per problem worth naming, in the order a reader should meet them. Already sentences. */
  paragraphs: { lead: string; body: string }[];
  /** What to do, ranked. Empty when nothing is wrong, which is itself worth saying. */
  actions: string[];
  /** The question the tab answers, shown above the headline. */
  question: string;
};

/** Worst first, then by how much the metric matters. A tie is broken by weight, never by order written. */
function ranked(metrics: Metric[], weights: Record<string, number>): { m: Metric; s: Severity }[] {
  const rank: Record<Severity, number> = { bad: 0, watch: 1, good: 2 };
  return metrics
    .map((m) => ({ m, s: statusOf(m.value, m.bands) }))
    .filter((x): x is { m: Metric; s: Severity } => x.s !== null)
    .sort((a, b) => rank[a.s] - rank[b.s] || (weights[b.m.key] ?? 1) - (weights[a.m.key] ?? 1));
}

/**
 * ONE ACTION PER PROBLEM, and none that the app cannot stand behind.
 *
 * Every line is a thing the client can do this quarter, phrased as an instruction rather than an
 * observation — "bring debtor days down" rather than "debtor days are high", which the card above already
 * said. Nothing here invents a number: where an action needs one, it points at the screen that holds it.
 */
const ACTIONS: Record<string, string> = {
  /* Grow */
  operatingMargin: "Fix the loss before growing into it — this is the one thing on the page that has to change first.",
  lowestCash: "Fix the low month before anything else — bring invoicing forward, stage the spending, or arrange an overdraft to cover it.",
  cashConversion: "Chase the gap between profit and cash: it is sitting in unpaid invoices or in stock.",
  cashCycle: "Shorten the cycle — invoice on delivery, tighten terms, or hold less stock. Every day taken out is cash back.",
  workingCapitalPerDollar: "Every new sale is tying up cash. Ask for deposits or shorter terms on new work before you chase more of it.",
  returnOnPlan: "The spending does not earn enough. Stage it, or cut the part of it that is not tied to new revenue.",
  incrementalMargin: "Put a floor under the margin on new work, or the growth makes the business bigger and no better off.",
  operatingLeverage: "Overheads are growing with sales. Find the costs that should not have to rise before you add more volume.",
  revenueGrowth: "There is no growth in the forecast to fund. Revisit the sales lines before using this page.",
  /* Borrow */
  dscr: "The loan is too large for this cash flow. Reduce it, lengthen the term, or wait until earnings support it.",
  dscrStressed: "Ask for interest-only for the first six to twelve months, so a soft year does not breach the cover.",
  capacity: "Fund the gap another way — asset finance against the equipment, owner equity, or staging the spend.",
  runway: "Build the cash buffer before drawing the loan. An overdraft costs little unused and is the cheapest insurance here.",
  leverage: "Total debt is heavy against earnings. Pay something down, or raise the earnings, before adding more.",
  lvr: "There is not enough security behind the loan. Offer more, or expect the lender to lend less.",
  quickRatio: "Short-term bills depend on shifting stock. Collect faster, or hold less.",
  currentRatio: "Short-term obligations are close to short-term assets. Watch it before taking on more.",
  interestCover: "Interest is eating the operating profit. Refinance or reduce before borrowing more.",
  /* Sell */
  priceMultiple: "Reset the price to the top of your comparable range, or wait and sell stronger numbers.",
  transferability: "Fix the weakest transferability factor before going to market. A buyer discounts for it far harder than you would.",
  normalisedMargin: "The margin is thin for a sale. Either improve it for a year, or expect the multiple to reflect it.",
  fcfYield: "At this price a buyer's money earns too little. The price is the thing to move.",
  recurringShare: "Convert repeat customers onto something contracted before you go to market — it is the cheapest value you can add.",
  largestCustomer: "Work out your largest customer's share from your sales ledger. If it is above 20%, secure that contract on assignable terms before a buyer asks.",
  freeCashFlow: "Thin free cash flow after keeping the assets going. A buyer will notice the capital this business needs.",
  roic: "The business earns little on the capital it ties up, which caps what anyone will pay for it.",
};

const HEAD = {
  grow: {
    none: "Not enough of the plan is filled in to judge the growth",
    bad: "The growth plan does not fund itself",
    watch: "Worth doing, but it will be tight on cash",
    good: "The growth stands up",
  },
  borrow: {
    none: "Not enough of the plan is filled in to judge the borrowing",
    bad: "This loan is more than the business can carry",
    watch: "Repays in the base case, with little cushion",
    good: "The business can carry this loan",
  },
  sell: {
    none: "Not enough of the plan is filled in to judge a sale",
    bad: "Not ready to sell at this price",
    watch: "Saleable, with work to do first",
    good: "This would stand up to a buyer",
  },
} as const;

const QUESTION = {
  grow: "Can the business increase profit while funding the cash, people and assets that growth needs?",
  borrow: "Can the business repay this loan on time, including if trading gets worse?",
  sell: "Would the earnings and the customers survive a change of owner, and is the price justified?",
} as const;

export function verdict(
  kind: CapabilityKind,
  metrics: Metric[],
  weights: Record<string, number>,
  score: number | null,
): Verdict {
  const question = QUESTION[kind];
  if (score === null) {
    return {
      question, headline: HEAD[kind].none, actions: [],
      paragraphs: [{
        lead: "Nothing here is guessed.",
        body: "Every figure on this page is read from your own forecast. Fill in your sales lines and costs and it answers itself — each card below already says what it is waiting for.",
      }],
    };
  }

  const order = ranked(metrics, weights);
  const problems = order.filter((x) => x.s !== "good");
  const band: Severity = score < 50 ? "bad" : score < 70 ? "watch" : "good";

  /*
   * THE GOOD NEWS IS NAMED FIRST WHEN THERE IS ANY, because a page that opens on what is wrong reads as a
   * telling-off, and a client who has built something sound should be told so before being given a list.
   */
  const best = order.find((x) => x.s === "good");
  const paragraphs: Verdict["paragraphs"] = [];
  if (best && band !== "bad") paragraphs.push({ lead: `${best.m.name} is holding up.`, body: best.m.note });
  for (const p of problems.slice(0, 3)) paragraphs.push({ lead: `${p.m.name}.`, body: p.m.note });
  if (!problems.length) {
    paragraphs.push({
      lead: "Nothing is flagged.",
      body: "Every measure this page can compute sits in its healthy band. That is worth saying plainly — and worth re-reading once the forecast changes.",
    });
  }

  return {
    question,
    headline: HEAD[kind][band],
    paragraphs,
    actions: problems.map((p) => ACTIONS[p.m.key]).filter(Boolean).slice(0, 4),
  };
}
